List<Map<String, dynamic>> items = [
  {
    "id": 1,
    "title": "Tandoori Chicken Pizza",
    "restaurant": "Josh Pizzaria",
    "restaurant_type": "cafe",
    "rating_count": 4,
    "rating": 4.5,
    "cost": 400,
    "region": "NCR",
    "description": "A hearty pizza available in vegetarian and meat-lovers.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["vegetarian", "meat-lovers"],
    "bundle": ["real", "pizza3.jpg"]
  },
  {
    "id": 2,
    "title": "Pepperoni Pizza",
    "restaurant": "Pizza Express",
    "restaurant_type": "cafe",
    "rating_count": 10,
    "rating": 4.2,
    "cost": 350,
    "region": "NCR",
    "description": "A classic pizza with pepperoni topping.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["pepperoni"],
    "bundle": ["real", "pizza4.jpg"]
  },
  {
    "id": 3,
    "title": "Margherita Pizza",
    "restaurant": "Pizza Hut",
    "restaurant_type": "fast food",
    "rating_count": 12,
    "rating": 4.0,
    "cost": 300,
    "region": "NCR",
    "description":
        "A simple yet delicious pizza with tomatoes, mozzarella, and basil.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["tomatoes", "mozzarella", "basil"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 4,
    "title": "Hawaiian Pizza",
    "restaurant": "Pizza Hut",
    "restaurant_type": "fast food",
    "rating_count": 8,
    "rating": 4.3,
    "cost": 350,
    "region": "NCR",
    "description": "A pizza with ham and pineapple toppings.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["ham", "pineapple"],
    "bundle": ["real", "pizza.jpg"]
  },
  {
    "id": 5,
    "title": "Meat Lovers Pizza",
    "restaurant": "Shakey's Pizza",
    "restaurant_type": "restaurant",
    "rating_count": 6,
    "rating": 4.6,
    "cost": 450,
    "region": "NCR",
    "description":
        "A pizza with various meat toppings such as pepperoni, saNCRge, ham, and bacon.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["pepperoni", "saNCRge", "ham", "bacon"],
    "bundle": ["real", "pizza4.jpg"]
  },
  {
    "id": 6,
    "title": "Veggie Pizza",
    "restaurant": "Yellow Cab Pizza Co.",
    "restaurant_type": "restaurant",
    "rating_count": 7,
    "rating": 4.4,
    "cost": 400,
    "region": "NCR",
    "description":
        "A pizza with various vegetable toppings such as onions, peppers, mushrooms, and olives.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["onions", "peppers", "mushrooms", "olives"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 7,
    "title": "Beef and Mushroom Burger",
    "restaurant": "Burger Joint",
    "restaurant_type": "fast food",
    "rating_count": 15,
    "rating": 4.2,
    "cost": 300,
    "region": "NCR",
    "description":
        "Juicy beef patty with sautéed mushrooms, served on a sesame seed bun.",
    "portions": ["single", "double"],
    "ingredients": [
      "beef patty",
      "mushrooms",
      "lettuce",
      "tomatoes",
      "cheddar cheese",
      "mayonnaise",
      "ketchup",
      "sesame seed bun"
    ],
    "bundle": ["real", "hamburger.jpg"]
  },
  {
    "id": 8,
    "title": "Mushroom & Feta Pizza",
    "restaurant": "Pizza Hut",
    "restaurant_type": "cafe",
    "rating_count": 6,
    "rating": 4.1,
    "cost": 370,
    "region": "NCR",
    "description": "A vegetarian pizza with fresh mushrooms and feta cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["vegetarian"],
    "bundle": ["real", "pizza3.jpg"]
  },
  {
    "id": 9,
    "title": "Pepperoni Pizza",
    "restaurant": "Pizza Hut",
    "restaurant_type": "cafe",
    "rating_count": 12,
    "rating": 4.8,
    "cost": 450,
    "region": "NCR",
    "description": "A classic pizza with pepperoni and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["meat"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 10,
    "title": "Margherita Pizza",
    "restaurant": "Pizza Hut",
    "restaurant_type": "cafe",
    "rating_count": 8,
    "rating": 4.6,
    "cost": 340,
    "region": "NCR",
    "description":
        "A simple pizza with tomato sauce, fresh basil, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["vegetarian"],
    "bundle": ["real", "pizza.jpg"]
  },
  {
    "id": 11,
    "title": "Meatball Pizza",
    "restaurant": "Shakey's Pizza",
    "restaurant_type": "cafe",
    "rating_count": 5,
    "rating": 3.9,
    "cost": 420,
    "region": "NCR",
    "description":
        "A pizza with meatballs, tomato sauce, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["meat"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 12,
    "title": "Hawaiian Pizza",
    "restaurant": "Shakey's Pizza",
    "restaurant_type": "cafe",
    "rating_count": 10,
    "rating": 4.4,
    "cost": 390,
    "region": "NCR",
    "description":
        "A pizza with pineapple, ham, tomato sauce, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["meat"],
    "bundle": ["real", "pizza3.jpg"]
  },
  {
    "id": 13,
    "title": "Chicken Alfredo Pizza",
    "restaurant": "Yellow Cab Pizza",
    "restaurant_type": "cafe",
    "rating_count": 9,
    "rating": 4.2,
    "cost": 500,
    "region": "NCR",
    "description":
        "A pizza with chicken, alfredo sauce, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["meat"],
    "bundle": ["real", "pizza4.jpg"]
  },
  {
    "id": 14,
    "title": "Margherita Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 5,
    "rating": 4.8,
    "cost": 350,
    "region": "CAR",
    "description":
        "A classic pizza with tomato sauce, mozzarella cheese, and basil leaves.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["tomato sauce", "mozzarella cheese", "basil leaves"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 15,
    "title": "Pepperoni Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 6,
    "rating": 4.7,
    "cost": 400,
    "region": "NCR",
    "description": "A pizza topped with spicy pepperoni and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["pepperoni", "mozzarella cheese"],
    "bundle": ["real", "pizza.jpg"]
  },
  {
    "id": 16,
    "title": "Chicken Alfredo Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 4,
    "rating": 4.5,
    "cost": 450,
    "region": "NCR",
    "description":
        "A pizza topped with chicken, alfredo sauce, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["chicken", "alfredo sauce", "mozzarella cheese"],
    "bundle": ["real", "pizza3.jpg"]
  },
  {
    "id": 17,
    "title": "Meatball Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 3,
    "rating": 4.2,
    "cost": 500,
    "region": "CAR",
    "description":
        "A pizza topped with meatballs, tomato sauce, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["meatballs", "tomato sauce", "mozzarella cheese"],
    "bundle": ["real", "pizza4.jpg"]
  },
  {
    "id": 18,
    "title": "Veggie Lovers Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 2,
    "rating": 4.0,
    "cost": 400,
    "region": "NCR",
    "description":
        "A pizza loaded with fresh vegetables such as mushrooms, onions, peppers, and olives.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["mushrooms", "onions", "peppers", "olives"],
    "bundle": ["real", "pizza2.jpg"]
  },
  {
    "id": 19,
    "title": "Hawaiian Pizza",
    "restaurant": "Pizza House",
    "restaurant_type": "cafe",
    "rating_count": 8,
    "rating": 4.6,
    "cost": 450,
    "region": "NCR",
    "description": "A pizza topped with ham, pineapple, and mozzarella cheese.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["ham", "pineapple", "mozzarella cheese"],
    "bundle": ["real", "pizza.jpg"]
  },
  {
    "id": 20,
    "title": "Vegetable Curry",
    "restaurant": "Spice House",
    "restaurant_type": "restaurant",
    "rating_count": 10,
    "rating": 4.7,
    "cost": 300,
    "region": "CAR",
    "description":
        "A classic vegetable curry made with fresh vegetables and spices.",
    "portions": ["small", "medium", "large"],
    "ingredients": ["cauliflower", "carrots", "potatoes", "peas"],
    "bundle": ["real", "rice.jpg"]
  }
];
